-- Insert Data Into Table Article --	
INSERT INTO article(title, description, thumbnail) VALUES('Such, Such Were the Joys', 'Consectetur ut molestiae laudantium qui qui consequatur aut.', 'http://lorempixel.com/100/100/fashion/');
INSERT INTO article(title, description, thumbnail) VALUES('Beneath the Bleeding', 'Temporibus laboriosam molestiae.', 'http://lorempixel.com/100/100/people/');
INSERT INTO article(title, description, thumbnail) VALUES('Down to a Sunless Sea', 'Quas qui cum delectus ex quod sint.', 'http://lorempixel.com/100/100/business/');
INSERT INTO article(title, description, thumbnail) VALUES('The Heart Is a Lonely Hunter', 'Quo dolores maxime eaque nostrum excepturi quia.', 'http://lorempixel.com/100/100/sports/');
INSERT INTO article(title, description, thumbnail) VALUES('Mother Night', 'Nobis enim quo ratione itaque.', 'http://lorempixel.com/100/100/cats/');
INSERT INTO article(title, description, thumbnail) VALUES('The Stars Tennis Balls', 'Quas vel magni laboriosam.', 'http://lorempixel.com/100/100/food/');
INSERT INTO article(title, description, thumbnail) VALUES('An Evil Cradling', 'Facilis quod omnis et.', 'http://lorempixel.com/100/100/sports/');
INSERT INTO article(title, description, thumbnail) VALUES('The Moving Finger', 'Dolores atque maiores aut sunt optio et temporibus.', 'http://lorempixel.com/100/100/nightlife/');
INSERT INTO article(title, description, thumbnail) VALUES('The Lathe of Heaven', 'Ullam sunt voluptates quod architecto ex.', 'http://lorempixel.com/100/100/animals/');
INSERT INTO article(title, description, thumbnail) VALUES('The Heart Is Deceitful Above All Things', 'Occaecati consequatur nam.', 'http://lorempixel.com/100/100/city/');
INSERT INTO article(title, description, thumbnail) VALUES('Its a Battlefield', 'Et possimus perspiciatis rerum soluta odit similique sapiente.', 'http://lorempixel.com/100/100/sports/');
INSERT INTO article(title, description, thumbnail) VALUES('The Curious Incident of the Dog in the Night-Time', 'Delectus debitis modi suscipit necessitatibus iste maxime.', 'http://lorempixel.com/100/100/transport/');
INSERT INTO article(title, description, thumbnail) VALUES('The Grapes of Wrath', 'Explicabo expedita ea explicabo aspernatur praesentium veritatis enim.', 'http://lorempixel.com/100/100/fashion/');
INSERT INTO article(title, description, thumbnail) VALUES('A Handful of Dust', 'Molestiae aut ut voluptatem ut.', 'http://lorempixel.com/100/100/nature/');
INSERT INTO article(title, description, thumbnail) VALUES('Butter In a Lordly Dish', 'Dolorem ipsam quam.', 'http://lorempixel.com/100/100/transport/');
INSERT INTO article(title, description, thumbnail) VALUES('Butter In a Lordly Dish', 'Recusandae soluta corporis nulla sit itaque explicabo harum.', 'http://lorempixel.com/100/100/sports/');
INSERT INTO article(title, description, thumbnail) VALUES('A Time to Kill', 'Vitae nihil porro.', 'http://lorempixel.com/100/100/cats/');
INSERT INTO article(title, description, thumbnail) VALUES('The Sun Also Rises', 'Aut quia sed aut ab voluptates.', 'http://lorempixel.com/100/100/people/');
INSERT INTO article(title, description, thumbnail) VALUES('As I Lay Dying', 'Temporibus itaque tempore.', 'http://lorempixel.com/100/100/nature/');
INSERT INTO article(title, description, thumbnail) VALUES('Infinite Jest', 'Magni eius accusamus et quisquam nihil et.', 'http://lorempixel.com/100/100/fashion/');
INSERT INTO article(title, description, thumbnail) VALUES('As I Lay Dying', 'Mollitia in debitis.', 'http://lorempixel.com/100/100/fashion/');
INSERT INTO article(title, description, thumbnail) VALUES('Eyeless in Gaza', 'Aut qui maxime harum.', 'http://lorempixel.com/100/100/city/');
INSERT INTO article(title, description, thumbnail) VALUES('In Death Ground', 'Ipsa deserunt dolorem.', 'http://lorempixel.com/100/100/nightlife/');
INSERT INTO article(title, description, thumbnail) VALUES('Oh! To be in England', 'Voluptatem aut in sapiente facilis aspernatur vero.', 'http://lorempixel.com/100/100/sports/');
INSERT INTO article(title, description, thumbnail) VALUES('The Wives of Bath', 'Magnam sed dolores placeat minus nemo corrupti asperiores.', 'http://lorempixel.com/100/100/abstract/');
INSERT INTO article(title, description, thumbnail) VALUES('Some Buried Caesar', 'Ad voluptatem placeat qui qui.', 'http://lorempixel.com/100/100/nightlife/');
INSERT INTO article(title, description, thumbnail) VALUES('Cabbages and Kings', 'Labore quod iure ducimus non consectetur.', 'http://lorempixel.com/100/100/nightlife/');
INSERT INTO article(title, description, thumbnail) VALUES('Look Homeward, Angel', 'Sed dolores est neque explicabo ea aperiam vitae.', 'http://lorempixel.com/100/100/fashion/');
INSERT INTO article(title, description, thumbnail) VALUES('An Evil Cradling', 'Officiis quasi nobis et dolores eveniet.', 'http://lorempixel.com/100/100/people/');
INSERT INTO article(title, description, thumbnail) VALUES('Tiger! Tiger!', 'Cumque corrupti suscipit nostrum sint est et dolorem.', 'http://lorempixel.com/100/100/people/');
